/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "http_test.check" instead.
 */

#include <check.h>

#line 1 "http_test.check"
#include "../src/http.c"

START_TEST(test_index)
{
#line 4
  ck_assert_str_eq(request("GET /index.html HTTP/1.0"), "HTTP/1.0 200 OK");
#
}
END_TEST

START_TEST(test_root)
{
#line 7
  ck_assert_str_eq(request("GET / HTTP/1.0"), "HTTP/1.0 200 OK");

}
END_TEST

START_TEST(test_get_subdir)
{
#line 10
  ck_assert_str_eq(request("GET /gnu/main.html HTTP/1.0"), "HTTP/1.0 200 OK");

}
END_TEST

START_TEST(test_404)
{
#line 13
  ck_assert_str_eq(request("GET /nofile HTTP/1.0"), "HTTP/1.0 404 Not Found");

}
END_TEST

START_TEST(test_404_subdir)
{
#line 16
  ck_assert_str_eq(request("GET /gnu/nofile HTTP/1.0"), "HTTP/1.0 404 Not Found");

}
END_TEST

START_TEST(test_http_verb_insensitivity)
{
#line 19
  ck_assert_str_eq(request("get / http/1.0"), "HTTP/1.0 200 OK");

}
END_TEST

START_TEST(test_case_sensitivity)
{
#line 22
  ck_assert_str_eq(request("GET /Index.html HTTP/1.0"), "HTTP/1.0 404 Not Found");

}
END_TEST

START_TEST(test_malformed_request)
{
#line 25
  ck_assert_str_eq(request("GET http.request HTTP/1.0"), "HTTP/1.0 400 Bad Request");

}
END_TEST

START_TEST(test_unreadable_file)
{
#line 28
  ck_assert_str_eq(request("GET /cantRead HTTP/1.0"), "HTTP/1.0 404 Not Found");

}
END_TEST

START_TEST(test_version_mismatch)
{
#line 31
  ck_assert_str_eq(request("GET /index.html HTTP/1.1"), "HTTP/1.0 400 Bad Request");

}
END_TEST

START_TEST(test_directory_and_version_mismatch)
{
#line 34
  ck_assert_str_eq(request("GET /gnu/ HTTP/1.1"), "HTTP/1.0 400 Bad Request");

}
END_TEST

START_TEST(test_no_such_verb)
{
#line 37
  ck_assert_str_eq(request("got / http/1.0"), "HTTP/1.0 400 Bad Request");

}
END_TEST

START_TEST(test_cant_read_parent)
{
#line 40
  ck_assert_str_eq(request("GET /../ HTTP/1.0"), "HTTP/1.0 404 Not Found");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_index);
    tcase_add_test(tc1_1, test_root);
    tcase_add_test(tc1_1, test_get_subdir);
    tcase_add_test(tc1_1, test_404);
    tcase_add_test(tc1_1, test_404_subdir);
    tcase_add_test(tc1_1, test_http_verb_insensitivity);
    tcase_add_test(tc1_1, test_case_sensitivity);
    tcase_add_test(tc1_1, test_malformed_request);
    tcase_add_test(tc1_1, test_unreadable_file);
    tcase_add_test(tc1_1, test_version_mismatch);
    tcase_add_test(tc1_1, test_directory_and_version_mismatch);
    tcase_add_test(tc1_1, test_no_such_verb);
    tcase_add_test(tc1_1, test_cant_read_parent);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
